### ISSUE TITLE
Failing to initialize user id with value returned from API

### ISSUE THREAD

**Issue by MrRobo24** [cessinideveloper/Myworld#5]
Branch: auth-branch

Response , Data Class Object and DB Insertion:
![image](https://user-images.githubusercontent.com/54929439/104264048-e4879480-54b0-11eb-960d-81f614490740.png)

Data Class:
![image](https://user-images.githubusercontent.com/54929439/104264530-d6864380-54b1-11eb-89e9-6c7a028007d1.png)

SignInResponseBody dataclass has this user id, but it is not getting initialized with actual API response value although rest of the data members are working properly.

- [x] Initialize userId with received value
- [x] Need clarification on what to do with SignUpResponse
- [x] Push DB task on a different thread

**Comment by pranshu0402** [comment]
make data class userId value to user_id.

**Comment by MrRobo24** [comment]
@pranshu0402 done. It worked.
